apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: eureka-client
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: eureka-client
    spec:
      containers:
      - name: eureka-client
        image: luozuyi/eureka-client
        ports:
        - containerPort: 8088