apiVersion: v1
kind: Pod  # 副本控制器 RC
metadata:
  name: eureka # 
spec:
  containers:  # Pod 内容的定义部分
  - name: eureka #容器的名称
    image: luozuyi/eureka:latest #容器对应的 Docker Image
    ports:
    - containerPort: 8761 # 容器暴露的端口号
