apiVersion: v1
kind: Service
metadata:
  name: eureka-service
spec:
  ports:
  - port: 8761
    protocol: TCP
    targetPort: 8761
    nodePort: 8761
  type: NodePort
  selector:
    app: eureka-service

---

 apiVersion: extensions/v1beta1
 kind: Deployment
 metadata:
   name: eureka-deployment
 spec:
   replicas: 1
   template:
     metadata:
       labels:
         app: eureka
     spec:
       containers:
       - name: eureka
         image: luozuyi/eureka
         ports:
         - containerPort: 8761